{% set name = "pycsvy" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycsvy-{{ version }}.tar.gz
  sha256: 21271402c1f7d975581a9cddebf48921cb3f4bda14246be8ed0bbcc0c4cc7f6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml >=6.0.0,<7.0.0
    - pydantic >=2.9.2,<3.0.0
  run_constrained:
    - numpy >=1.24.2,<3.0.0
    - pandas >=2.0.0,<3.0.0
    - polars >=1.8.2,<2.0.0

test:
  imports:
    - csvy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pycsvy/
  summary: Python reader/writer for CSV files with YAML header information.
  dev_url: https://github.com/ImperialCollegeLondon/pycsvy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalonsoa
